apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-cdc-iceberg
spec:
  image: abyssnlp/flink-cdc-iceberg:0.1
  flinkVersion: v1_20
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2Gi"
      cpu: 1
  taskManager:
    resource:
      memory: "2Gi"
      cpu: 1
  job:
    jarURI: local:///opt/flink-jobs/flink-cdc-iceberg-1.0.jar
    parallelism: 1
    upgradeMode: stateless