FROM bitnami/postgresql:15

USER root

RUN apt-get update && apt-get install -y \
    protobuf-c-compiler \
    libprotobuf-c-dev \
    build-essential gcc clang llvm git make pkg-config && \
    git clone https://github.com/debezium/postgres-decoderbufs -b v3.1.0.Alpha2 --single-branch && \
    (cd postgres-decoderbufs && make && make install) && \
    rm -rf postgres-decoderbufs && \
    apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER 1001